"""
Constants Module

Centralized location for all constants used throughout the cap table generator.
"""

# Calculation Types
CALC_TYPE_FIXED_SHARES = "fixed_shares"
CALC_TYPE_TARGET_PERCENTAGE = "target_percentage"
CALC_TYPE_VALUATION_BASED = "valuation_based"
CALC_TYPE_CONVERTIBLE = "convertible"
CALC_TYPE_SAFE = "safe"

CALCULATION_TYPES = [
    CALC_TYPE_FIXED_SHARES,
    CALC_TYPE_TARGET_PERCENTAGE,
    CALC_TYPE_VALUATION_BASED,
    CALC_TYPE_CONVERTIBLE,
    CALC_TYPE_SAFE,
]

# Pro Rata Types
PRO_RATA_NONE = "none"
PRO_RATA_STANDARD = "standard"
PRO_RATA_SUPER = "super"

PRO_RATA_TYPES = [
    PRO_RATA_NONE,
    PRO_RATA_STANDARD,
    PRO_RATA_SUPER,
]

# Exercise Types
EXERCISE_FULL = "full"
EXERCISE_PARTIAL = "partial"

EXERCISE_TYPES = [
    EXERCISE_FULL,
    EXERCISE_PARTIAL,
]

# Valuation Basis
VALUATION_BASIS_PRE_MONEY = "pre_money"
VALUATION_BASIS_POST_MONEY = "post_money"

VALUATION_BASIS_TYPES = [
    VALUATION_BASIS_PRE_MONEY,
    VALUATION_BASIS_POST_MONEY,
]

# Interest Types
INTEREST_NONE = "no_interest"
INTEREST_SIMPLE = "simple"
INTEREST_COMPOUND_YEARLY = "compound_yearly"
INTEREST_COMPOUND_MONTHLY = "compound_monthly"
INTEREST_COMPOUND_DAILY = "compound_daily"

INTEREST_TYPES = [
    INTEREST_NONE,
    INTEREST_SIMPLE,
    INTEREST_COMPOUND_YEARLY,
    INTEREST_COMPOUND_MONTHLY,
    INTEREST_COMPOUND_DAILY,
]

# Valuation Cap Types
VALUATION_CAP_DEFAULT = "default"
VALUATION_CAP_PRE_CONVERSION = "pre_conversion"
VALUATION_CAP_POST_CONVERSION_OWN = "post_conversion_own"
VALUATION_CAP_POST_CONVERSION_TOTAL = "post_conversion_total"

VALUATION_CAP_TYPES = [
    VALUATION_CAP_DEFAULT,
    VALUATION_CAP_PRE_CONVERSION,
    VALUATION_CAP_POST_CONVERSION_OWN,
    VALUATION_CAP_POST_CONVERSION_TOTAL,
]

# Error Codes
ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_CODE_FORMULA_GENERATION = "FORMULA_GENERATION_ERROR"
ERROR_CODE_REFERENCE_RESOLUTION = "REFERENCE_RESOLUTION_ERROR"
ERROR_CODE_EXCEL_GENERATION = "EXCEL_GENERATION_ERROR"
ERROR_CODE_SCHEMA = "SCHEMA_ERROR"
ERROR_CODE_RELATIONSHIP = "RELATIONSHIP_ERROR"
ERROR_CODE_BUSINESS_RULE = "BUSINESS_RULE_ERROR"

# Excel Format Constants
EXCEL_DEFAULT_FONT_SIZE = 10
EXCEL_DEFAULT_BG_COLOR = "#869A78"
EXCEL_FONT_PT_SANS = "PT Sans"
EXCEL_FONT_CENTURY_GOTHIC = "Century Gothic"
EXCEL_HEADER_FONT_SIZE = 11
EXCEL_ROUND_HEADER_FONT_SIZE = 14

# Excel Sheet Names
SHEET_NAME_CAP_TABLE = "Cap Table"
SHEET_NAME_ROUNDS = "Rounds"
SHEET_NAME_PRO_RATA = "Pro Rata Allocations"

# Default Values
DEFAULT_INDENT = 2
DEFAULT_PADDING_OFFSET = 1

# Holder Groups (default order)
HOLDER_GROUP_FOUNDERS = "Founders"
HOLDER_GROUP_ESOP = "ESOP"
HOLDER_GROUP_NOTEHOLDERS = "Noteholders"
HOLDER_GROUP_INVESTORS = "Investors"

DEFAULT_HOLDER_GROUP_ORDER = [
    HOLDER_GROUP_FOUNDERS,
    HOLDER_GROUP_ESOP,
    HOLDER_GROUP_NOTEHOLDERS,
    HOLDER_GROUP_INVESTORS,
]

# Schema Version
SCHEMA_VERSION_2_0 = "2.0"
CURRENT_SCHEMA_VERSION = SCHEMA_VERSION_2_0





